-- 出账.sql::出账


-- 2022年10月至2024年3月期间，

DROP TABLE IF EXISTS PTEMP.SHENJI_ZDCBFYQS_27_02_D1;
CREATE TABLE PTEMP.SHENJI_ZDCBFYQS_27_02_D1 AS 
SELECT K1.* 
FROM PMID5.TB_MID_FIN_DTL_USER_MON K1
INNER JOIN PMID.TB_MID_PAR_USER_MON K2 
ON K1.USER_ID = K2.USER_ID AND K1.DEAL_DATE = K2.DEAL_DATE AND K2.BELONG_TYPE_CODE='3' AND K2.DEAL_DATE  BETWEEN '202210' AND '202403' 
WHERE K1.DEAL_DATE BETWEEN '202210' AND '202403' 
;

DROP TABLE IF EXISTS PTEMP.SHENJI_ZDCBFYQS_27_02;
CREATE TABLE IF NOT EXISTS PTEMP.SHENJI_ZDCBFYQS_27_02(
    DEAL_DATE VARCHAR(8) COMMENT '日期'
    ,PHONE_NO VARCHAR(50) COMMENT '号码'
    ,REGION_CODE VARCHAR(10) COMMENT '归属地市'
    ,CITY_CODE VARCHAR(10) COMMENT '归属区县'
    ,REGION_DESC VARCHAR(50) COMMENT '地市名称'
    ,CITY_DESC VARCHAR(50) COMMENT '区县名称'
    ,USER_ID VARCHAR(50) COMMENT '用户ID'
    ,ACCT_ID VARCHAR(50) COMMENT '帐户ID'
    ,PROD_PRCID VARCHAR(50) COMMENT '产品资费代码'
    ,PROD_PRC_NAME VARCHAR(500) COMMENT '产品资费名称'
    ,GRP_CUST_ID VARCHAR(50) COMMENT '客户ID'
    ,CUST_NAME VARCHAR(600) COMMENT '客户名称'
    ,CUST_LEVEL VARCHAR(50) COMMENT '重要客户等级'
    ,TRADE_CODE VARCHAR(10) COMMENT '行业代码'
    ,TRADE_NAME VARCHAR(500) COMMENT '行业名称'
    ,ACCT_ITEM_CODE VARCHAR(10) COMMENT '账目项'
    ,ACCT_ITEM_NAME VARCHAR(500) COMMENT '账目项名称'
    ,SHOULD_PAY DECIMAL(18,4) COMMENT '收入'
)DISTRIBUTED BY ('GRP_CUST_ID') COMMENT ='山西公司重点成本费用专项审计资料需求（第一批）-出帐';


INSERT INTO PTEMP.SHENJI_ZDCBFYQS_27_02(
    DEAL_DATE
    ,PHONE_NO
    ,REGION_CODE
    ,CITY_CODE
    ,REGION_DESC
    ,CITY_DESC
    ,USER_ID
    ,ACCT_ID
    ,PROD_PRCID
    ,PROD_PRC_NAME
    ,GRP_CUST_ID
    ,CUST_NAME
    ,CUST_LEVEL
    ,TRADE_CODE
    ,TRADE_NAME
    ,ACCT_ITEM_CODE
    ,ACCT_ITEM_NAME
    ,SHOULD_PAY 
)
SELECT 
    K1.DEAL_DATE AS DEAL_DATE -- 日期
    ,K1.PHONE_NO AS PHONE_NO -- 号码
    ,K1.REGION_CODE AS REGION_CODE -- 归属地市
    ,K1.CITY_CODE AS CITY_CODE -- 归属区县
    ,DS.REGION_DESC AS REGION_DESC -- 地市名称
    ,QX.CITY_DESC AS CITY_DESC -- 区县名称
    ,K1.USER_ID AS USER_ID -- 用户ID
    ,K1.ACCT_ID AS ACCT_ID -- 帐户ID
    ,K1.PROD_PRCID AS PROD_PRCID -- 产品资费代码
    ,K3.PROD_PRC_NAME AS PROD_PRC_NAME -- 产品资费名称
    ,K2.CUST_ID AS GRP_CUST_ID -- 客户ID
    ,T6.CUST_NAME AS CUST_NAME   -- 客户名称
    ,K5.CUST_LEVEL AS CUST_LEVEL -- 重要客户等级
    ,K5.TRADE_CODE AS TRADE_CODE -- 行业代码
    ,T3.CODE_NAME AS TRADE_NAME -- 行业名称
    ,K1.V20_ACCT_ITEM_CLS||K1.V20_RPT_ACCT_ITEM_GRP  AS ACCT_ITEM_CODE -- 账目项
    ,T5.ITEM_NAME AS ACCT_ITEM_NAME -- 账目项名称
    ,SUM(K1.SHOULD_PAY) AS SHOULD_PAY -- 收入
FROM PTEMP.SHENJI_ZDCBFYQS_27_02_D1 K1
INNER JOIN PMID.TB_MID_PAR_USER_MON K2
ON K1.USER_ID = K2.USER_ID AND K1.DEAL_DATE = K2.DEAL_DATE AND K2.BELONG_TYPE_CODE='3'  AND K2.DEAL_DATE  BETWEEN '202210' AND '202403' 
LEFT JOIN PDATA.TB_PDT_PRC_INFO_DAY K3
ON K1.PROD_PRCID = K3.PROD_PRCID
LEFT JOIN  PCDE.TB_CDE_FIN_ITEM_CONF T5
ON K1.V20_ACCT_ITEM_CLS||K1.V20_RPT_ACCT_ITEM_GRP = T5.ACCT_ITEM_CODE 
LEFT JOIN PCDE.TB_CDE_LOC_REGION DS
ON DS.REGION_CODE = K1.REGION_CODE
LEFT JOIN PCDE.TB_CDE_LOC_CITY QX
ON QX.REGION_CODE =K1.REGION_CODE AND QX.CITY_CODE = K1.CITY_CODE
LEFT JOIN PDATA.TB_PAR_CUST_INFO_EXT_DAY T6
ON K2.CUST_ID = T6.CUST_ID 
LEFT JOIN PMID5.TB_MID_GRP_CUST_INFO_MON K5
ON K2.CUST_ID = K5.CUST_ID AND K5.DEAL_DATE='202403'
LEFT JOIN( -- >> 行业编码码表 
SELECT 
        T3.CODE_VALUE AS CODE_VALUE -- 代码值 
        ,T3.CODE_NAME AS CODE_NAME -- 代码名称 
    FROM PCDE.TB_CDE_UNI_DAY T3 
    WHERE CODE_CLASS=181 -- 代码分类编码 
    AND DATA_BELONG='CRMATEST' -- 数据来源 
    GROUP BY 1,2 
)T3 
ON K5.TRADE_CODE = T3.CODE_VALUE
WHERE K1.DEAL_DATE BETWEEN '202210' AND '202403' 
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
;




-- 解密

UPDATE PTEMP.SHENJI_ZDCBFYQS_27_02  T1
SET T1.CUST_NAME = PTEMP.AES_DEC(T1.CUST_NAME)
;

UPDATE PTEMP.SHENJI_ZDCBFYQS_27_02 T1 
,PMID.DATADECRYPT K 
SET T1.PHONE_NO = SUBSTRING( T1.PHONE_NO ,1,LENGTH( T1.PHONE_NO )-4)||K.LAST_NUM 
WHERE SUBSTRING( T1.PHONE_NO ,LENGTH( T1.PHONE_NO )-3,4)=TRIM(K.DECR_STR); 


SELECT SUM(SHOULD_PAY) FROM PTEMP.SHENJI_ZDCBFYQS_27_02;
SELECT SUM(SHOULD_PAY) FROM PTEMP.SHENJI_ZDCBFYQS_27_02_D1;


-- 出帐 SELECT * FROM  PTEMP.SHENJI_ZDCBFYQS_27_02;